name: Testing Debug GCC
on: [push, workflow_dispatch]

jobs:
  test-app-gcc-debug:
    runs-on: ubuntu-latest
    env:
      TESTING: 1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install conan
        run: pip install conan

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: install cmake
        run: sudo apt install -y cmake

      - name: checkout cpp_click
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/FelixTheC/cpp_click

      - name: run ls
        working-directory: ./
        run: ls -l

      - name: build cmake
        working-directory: ./
        run: |
          mkdir build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
          make -j2

      - name: run test
        working-directory: ./
        run: ls -l
